04_TemplateExam/TemplateApp/urls.py
from django.urls import path
from.import views

app_name = 'app'

urlpatterns = [
    path('home', views.home, name='home'),
    path('members', views.members, name='members'),
    path('member/<int:id>', views.member, name='member'),
]

04_TemplateExam/TemplateExam/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('TemplateApp.urls')),
]

04_TemplateExam/TemplateApp/models.py
from django.db import models

# Create your models here.

04_TemplateExam/TemplateApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

class Member:
    
    def __init__(self, id, name, join_at,picture_path):
        self.id = id
        self.name = name
        self.join_at = join_at
        self.picture_path = picture_path

member_list = [
    Member(0,'Taro','2018/04/01','img/taro.jpg'),
    Member(1,'Jiro','2019/04/01','img/jiro.jpg'),
    Member(2,'Hanako','2019/10/01','img/hanako.jpg'),
    Member(3,'Yoshiko','2018/10/01','img/yoshiko.jpg'),
]       



#ホーム画面
def home(request):
    return render(request,'home.html')


#メンバー一覧
def members(request):
    return render(request,'members.html',context={
        'members':member_list
    })


#メンバー詳細
def member(request,id):
    for member in member_list:
        if member.id == id:
            return render(request,'member_detail.html',context={
                'member':member
            })
            
    return HttpResponse('Not Found' ,status=404)

04_TemplateExam/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{%block title %}大学陸上部{%endblock%}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>    
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href={% url 'app:home' %}>Home</a>
                <a class="navbar-brand" href={% url 'app:members' %}>メンバー一覧</a>
            </div>
        </nav>
        {% block content %}{% endblock %}        
    </body>
</html>

04_TemplateExam/templates/home.html
{% extends "base.html" %}
{% block title %}Home{{ block.super }}{% endblock %}
{% block content %}
    <p>大学陸上部のホームページへようこそ！</p>
{% endblock %}

04_TemplateExam/templates/member_detail.html
{% extends "base.html" %}
{% block title %}メンバー詳細{{ block.super }}{% endblock %}
{% load static %}

{% load custom_tags %}
{% block content %}

   <h1>メンバー詳細</h1>
   <img src="{% static member.picture_path %}" >
    <p>名前: {{ member.name }}</p>
    <p>入部日：{{ member.join_at }}</p>
    <p>入部から：{{ member.join_at|calucurate_datetime_to_now }}</p>
{% endblock %}

04_TemplateExam/templates/members.html
{% extends "base.html" %}
{% block title %}メンバー一覧{{ block.super }}{% endblock %}
{% block content %}
    {% for member in members %}
    <p><a href="{% url 'app:member' id=member.id %}">{{ member.name }}</a></p>
    {% endfor %}
{% endblock %}