03_Template/Templateproject/TemplateApp/urls.py
from django.urls import path
from . import views

app_name = 'template_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/<first_name>/<last_name>', views.home, name='home'),
    path('sample1/', views.sample1, name='sample1'),  # 末尾にスラッシュを追加
    path('sample2/', views.sample1, name='sample2'), 
    path('sample/', views.sample, name='sample'),
    path('sample3/', views.sample3, name='sample3'), 
]

03_Template/Templateproject/TemplateProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'template_app/', include( 'TemplateApp.urls' ) ),
]

03_Template/Templateproject/TemplateApp/views.py
from django.shortcuts import render

# Create your views here.
def index( request ):
    value = "Good Morning"
    return render( request, 'TemplateApp/index.html', context ={"value":value} )


#home関数を作る

def home(request, first_name, last_name):
    my_name = f'{first_name} {last_name}'
  
    favorite_fruit = ['Apple', 'Banana', 'Orange']
    my_info = {'name': first_name, 'age': 25}
    
    
    status = 20
    
    return render(request, 'TemplateApp/home.html', 
                 context={'my_name': my_name, 'favorite_fruit': favorite_fruit, 'my_info': my_info, 'status': status})


#sample1関数を作る
def sample1(request):
    return render(request, 'TemplateApp/sample1.html')


#sample2関数を作る
def sample1(request):
    return render(request, 'TemplateApp/sample2.html')


#テンプレートフィルターの練習　sample関数を作る
def sample(request):
    name = 'Ichiro Yamada'
    height = 175.5
    weight = 72
    bmi = weight / (height / 100) ** 2  
    page_url = 'https://www.google.com/'
    favorite_fruits = ['Apple', 'Grape', 'Lemon'] 
    msg = """Hello, 
    I'm Ichiro
    Yamada.""" 
    msg2 = '12134567890'
    
   
    return render(request, 'TemplateApp/sample.html', context={
        'name': name,
        'bmi': bmi,
        'page_url': page_url,
        'favorite_fruits': favorite_fruits,
        'msg': msg,
        'msg2': msg2
    })
    
    

# クラスを作る
class Country:
    def __init__(self, name, population, capital):
        self.name = name
        self.population = population
        self.capital = capital  # 引数はcapitalですが、attributeはareaになっています。修正しました


    def __str__(self):
        return f'{self.name} {self.population} {self.capital}'

    def capital_and_population(self):
        return f'capital: {self.capital},population:{self.population}'


# sample3関数を作る
def sample3(request):
    country = Country('Japan', 126800000, 'Tokyo')
    return render(request, 'TemplateApp/sample3.html', context={
        'country': country
    })

03_Template/Templateproject/TemplateApp/templates/app/index.html
<h1>Hello world</h1>

03_Template/Templateproject/templates/TemplateApp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}My Page{% endblock %}</title>
    </head>   
    <body>
        <h1>My Page</h1> 
        {% block content %}{% endblock %}
    </body>
</html>

03_Template/Templateproject/templates/TemplateApp/home.html
{% load filter %}
{% load static %}
{# <h1>Name: {{ my_name }}</h1> #}
{# <h2>果物: {{ favorite_fruit }}</h2> #}
{# <h3>Age: {{ my_info.age }}</h3> #}
{{ my_name }}
{# for #}

<ul>
    {% for fruit in favorite_fruit %}
        <li>{{ fruit }}</li>
    {% endfor %}
</ul>

{# if #}
{% if 'momo' in favorite_fruit %}
    <p>momoあります</p>
{% elif 'lemon' in favorite_fruit %}
    <p>lemonあります</p>
{% else %}
    <p>ありません</p>
{% endif %}


{% if 'age' in my_info %}
    <p>ageあります</p>
    {% if my_info.age > 20 %}
        <p>成年</p>
    {% endif %}
{% endif %}

{% if my_info.name != 'Yukiko Ishiguro！'%}
    <p>YUKIKOでない</p>
{% endif %}

<p> {{ status|status_to_string:'yukiko' }}</p>

<img src = "{% static 'static2/sample.jpg' %}" >

03_Template/Templateproject/templates/TemplateApp/index.html
<h1>goodbye</h1>

{{ value }}

03_Template/Templateproject/templates/TemplateApp/sample.html
{% load static %}

<link rel="stylesheet" type="text/css" href = "{% static 'static_file/css/sample.css'%}" %}">

<h1>{{ name|upper}}</h1>

<h1>{{ page_url|urlize}}</h1>

<p>BMI: {{ bmi|floatformat:2 }}</p>

<p>給料: {{ salary|default:"秘密"}}</p>

<P>{{favorite_fruits|random|lower}}</P>

<p>{{ favorite_fruits|join:',' }}</p>

<p>{{ msg|linebreaks}}</p>

<p>{{ msg2|truncatechars:3 }}</p>


<a href="{% url 'template_app:home' 'yamada' 'sato' %}">Home</a>


<img src = "{% static 'static_file/image/sample.jpg' %}" >

03_Template/Templateproject/templates/TemplateApp/sample1.html
{% extends "TemplateApp/base.html" %}

{% block title %} Sample1! {{ block.super }} {% endblock %}

{% block content %}
<p> Sample1 </p>
{% endblock %}

03_Template/Templateproject/templates/TemplateApp/sample2.html
{% extends "TemplateApp/base.html" %}

{% block title %} Sample2 {{ block.super }} {% endblock %}

{% block content %}
<p> Sample2 </p>
{% endblock %}

03_Template/Templateproject/templates/TemplateApp/sample3.html
<P>国名：{{ country.name }}</p>
<P>首都：{{ country.capital }}</p>
<P>人口：{{ country.population }}</p>


{{ country }}

{{ country.capital_and_population }}